# Generated by Django 2.2.4 on 2021-05-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
    ]
