# Generated by Django 2.2.4 on 2021-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_shell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='book', to='book_authors_shell.authors'),
        ),
    ]
