# Generated by Django 2.2.4 on 2021-05-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_shell', '0002_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='author_name',
        ),
    ]
