# Generated by Django 2.2.4 on 2021-05-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_shell', '0003_auto_20210524_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_name',
            new_name='author',
        ),
    ]
