# Generated by Django 2.2.4 on 2021-05-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_shell', '0004_auto_20210524_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
