# Generated by Django 2.2.4 on 2021-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='sdf', max_length=255),
            preserve_default=False,
        ),
    ]
