# Generated by Django 2.2.4 on 2021-05-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
