# Generated by Django 2.2.4 on 2021-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_wall_app', '0003_comments_messsages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='messsages_id',
            new_name='comment',
        ),
    ]
